query Profile($username:String){
  profiles(username:$username){
    _id
    alid
    username
    avatar
    banner
    level
    stats{
      completed
      minutesWatched
      episodesWatched
    }
    achievements{
      alid
      passedtier
      droppedtier
      magicalgirltier
      actiontier
      comedytier
      dramatier
      romancetier
      sliceOfLifetier
      fantasytier
      supernaturaltier
      sciFitier
      adventuretier
      mysterytier
      ecchitier
      psychologicaltier
      musictier
      thrillertier
      horrortier
      mechatier
      sportstier
    }
  }
}