const {Achievements,ProfileCompleteds} = require('../utils/models');
const updatePopularity = require('./updatePopularity')
exports.updateProfileAchievements = (alid,completedCount,droppedCount,mahouShoujoCount,actionCount,adventureCount,sliceOfLifeCount,fantasyCount,ecchiCount,mechaCount,mysteryCount)=>{
    updateProfileAchievements(alid,completedCount,droppedCount,mahouShoujoCount,actionCount,adventureCount,sliceOfLifeCount,fantasyCount,ecchiCount,mechaCount,mysteryCount)
}
function updateProfileAchievements(alid,completedCount,droppedCount,mahouShoujoCount,actionCount,adventureCount,sliceOfLifeCount,fantasyCount,ecchiCount,mechaCount,mysteryCount){
    if(completedCount>0){
        Achievements.findOne({type:"PASSED",max:{$gte:completedCount}},(err,res)=>{
          if(!res){
            Achievements.findOne({type:"PASSED",tier:11},(err,res)=>{
              ProfileCompleteds.findOneAndUpdate({alid:alid},{passedtier:res._id},{new:true},(err,data)=>{
                //console.log(data)
              })
            })
          }else{
            ProfileCompleteds.findOneAndUpdate({alid:alid},{passedtier:res._id},{new:true},(err,data)=>{
              //console.log(data)
            })
          }
        });
      }
      if(droppedCount>0){
        Achievements.findOne({type:"DROPPED",max:{$gte:droppedCount}},(err,res)=>{
          if(!res){
            Achievements.findOne({type:"DROPPED",tier:9},(err,res)=>{
              ProfileCompleteds.findOneAndUpdate({alid:alid},{droppedtier:res._id},{new:true},(err,data)=>{
                //console.log(data)
              })
            })
          }else{
            ProfileCompleteds.findOneAndUpdate({alid:alid},{droppedtier:res._id},{new:true},(err,data)=>{
              //console.log(data)
            })
          }
        });
      }else if(droppedCount == 0){
        Achievements.findOne({type:"DROPPED",tier:0},(err,res)=>{
          ProfileCompleteds.findOneAndUpdate({alid:alid},{droppedtier:res._id},{new:true},(err,data)=>{
            //console.log(data)
          })
        })
      }
      if(mahouShoujoCount>0){
        Achievements.findOne({type:"MAGICAL_GIRL",max:{$gte:mahouShoujoCount}},(err,res)=>{
          if(!res){
            Achievements.findOne({type:"MAGICAL_GIRL",tier:8},(err,res)=>{
              ProfileCompleteds.findOneAndUpdate({alid:alid},{magicalgirltier:res._id},{new:true},(err,data)=>{
                //console.log(data)
              })
            })
          }else{
            ProfileCompleteds.findOneAndUpdate({alid:alid},{magicalgirltier:res._id},{new:true},(err,data)=>{
              //console.log(data)
            })
          }
        })
      }
      if(actionCount>0){
        Achievements.findOne({type:"ACTION",max:{$gte:actionCount}},(err,res)=>{
          if(!res){
            Achievements.findOne({type:"ACTION",tier:8},(err,res)=>{
              ProfileCompleteds.findOneAndUpdate({alid:alid},{actiontier:res._id},{new:true},(err,data)=>{
                //console.log(data)
              })
            })
          }else{
            ProfileCompleteds.findOneAndUpdate({alid:alid},{actiontier:res._id},{new:true},(err,data)=>{
              //console.log(data)
            })
          }
        })
      }
      if(adventureCount>0){
        Achievements.findOne({type:"ADVENTURE",max:{$gte:adventureCount}},(err,res)=>{
          if(!res){
            Achievements.findOne({type:"ADVENTURE",tier:8},(err,res)=>{
              ProfileCompleteds.findOneAndUpdate({alid:alid},{adventuretier:res._id},{new:true},(err,data)=>{
                //console.log(data)
              })
            })
          }else{
            ProfileCompleteds.findOneAndUpdate({alid:alid},{adventuretier:res._id},{new:true},(err,data)=>{
              //console.log(data)
            })
          }
        })
      }
      if(sliceOfLifeCount>0){
        Achievements.findOne({type:"SLICE_OF_LIFE",max:{$gte:sliceOfLifeCount}},(err,res)=>{
          if(!res){
            Achievements.findOne({type:"SLICE_OF_LIFE",tier:8},(err,res)=>{
              ProfileCompleteds.findOneAndUpdate({alid:alid},{sliceOfLifetier:res._id},{new:true},(err,data)=>{
                //console.log(data)
              })
            })
          }else{
            ProfileCompleteds.findOneAndUpdate({alid:alid},{sliceOfLifetier:res._id},{new:true},(err,data)=>{
              //console.log(data)
            })
          }
        })
      }
      if(fantasyCount>0){
        Achievements.findOne({type:"FANTASY",max:{$gte:fantasyCount}},(err,res)=>{
          if(!res){
            Achievements.findOne({type:"FANTASY",tier:8},(err,res)=>{
              ProfileCompleteds.findOneAndUpdate({alid:alid},{fantasytier:res._id},{new:true},(err,data)=>{
                //console.log(data)
              })
            })
          }else{
            ProfileCompleteds.findOneAndUpdate({alid:alid},{fantasytier:res._id},{new:true},(err,data)=>{
              //console.log(data)
            })
          }
        })
      }
      if(ecchiCount>0){
        Achievements.findOne({type:"ECCHI",max:{$gte:ecchiCount}},(err,res)=>{
          if(!res){
            Achievements.findOne({type:"ECCHI",tier:8},(err,res)=>{
              ProfileCompleteds.findOneAndUpdate({alid:alid},{ecchitier:res._id},{new:true},(err,data)=>{
                //console.log(data)
              })
            })
          }else{
            ProfileCompleteds.findOneAndUpdate({alid:alid},{ecchitier:res._id},{new:true},(err,data)=>{
              //console.log(data)
            })
          }
        })
      }
      if(mechaCount>0){
        Achievements.findOne({type:"MECHA",max:{$gte:mechaCount}},(err,res)=>{
          if(!res){
            Achievements.findOne({type:"MECHA",tier:8},(err,res)=>{
              ProfileCompleteds.findOneAndUpdate({alid:alid},{mechatier:res._id},{new:true},(err,data)=>{
                //console.log(data)
              })
            })
          }else{
            ProfileCompleteds.findOneAndUpdate({alid:alid},{mechatier:res._id},{new:true},(err,data)=>{
              //console.log(data)
            })
          }
        })
      }
      if(mysteryCount>0){
        Achievements.findOne({type:"MYSTERY",max:{$gte:mysteryCount}},(err,res)=>{
          if(!res){
            Achievements.findOne({type:"MYSTERY",tier:8},(err,res)=>{
              ProfileCompleteds.findOneAndUpdate({alid:alid},{mysterytier:res._id},{new:true},(err,data)=>{
                //console.log(data)
              })
            })
          }else{
            ProfileCompleteds.findOneAndUpdate({alid:alid},{mysterytier:res._id},{new:true},(err,data)=>{
              //console.log(data)
            })
          }
        })
      }
      updatePopularity.updatePopularity(alid);
}